import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
    title: "Admin management",
    description: "Generated by create next app",
    icons: {
        icon: "/icon.png"
    }
};

const RootLayoutPage = ({
    children
}: { children: React.ReactNode }) => {
    return (
        <html >
            <link
                rel="icon"
                href="./icon.png"
                type="image/png"
                sizes="50x50"
            />
            <body>
                {children}
            </body>
        </html>
    )
}

export default RootLayoutPage