import { Toaster } from "@/components/ui/sonner";
import { authOptions } from "@/lib/auth/auth";
import DialogProvider from "@/providers/DialogProvider";
import DrawerProvider from "@/providers/DrawerProvider";
import "@fortawesome/fontawesome-free/css/all.min.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import AuthProvider from "../providers/AuthProvider";
import QueryClientProvider from "../providers/QueryProvider";
import ThemeProvider from "../providers/ThemeProvider";
import "./globals.css";


export const metadata: Metadata = {
  title: "Admin management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthProvider session={session}>
            <QueryClientProvider>
              <div className="relative">
                <main className="min-h-screen">{children}</main>
                <DialogProvider />
                <DrawerProvider />
                <Toaster />
              </div>
            </QueryClientProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
