import { Toaster } from "@/components/ui/sonner";
import DialogProvider from "@/providers/DialogProvider";
import DrawerProvider from "@/providers/DrawerProvider";
import "@fortawesome/fontawesome-free/css/all.min.css";
import type { Metadata } from "next";
import AuthProvider from "../providers/AuthProvider";
import QueryClientProvider from "../providers/QueryProvider";
import ThemeProvider from "../providers/ThemeProvider";
import "./globals.css";


export const metadata: Metadata = {
  title: "Admin management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children:React.ReactNode
}>) {
  
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthProvider session={null}>
            <QueryClientProvider>
              <main className="min-h-screen">{children}</main>
              <DialogProvider />
              <DrawerProvider />
              <Toaster />
            </QueryClientProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
